language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .

# command to run tests
script: make coverage

after_success:
  - coveralls

{% if cookiecutter.use_pypi_deployment_with_travis == "yes" -%}
# FIXME: untested and never used
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    condition: $TOXENV == py27
{%- endif %}
