
default_context:
    bitbucket_repo: "nicfit.py"
    bitbucket_url: "https://bitbucket.org/bitbucket-user/nicfit.py"
    bitbucket_username: "bitbucket-user"
    email: "travis@pobox.com"
    full_name: "Travis Shirk"
    github_repo: "nicfit.py"
    github_url: "https://github.com/nicfit/nicfit.py"
    github_username: "nicfit"
    intended_audience: "Developers"
    license: "MIT"
    project_long_description: ""
    project_name: "nicfit.py"
    project_short_description: "Common Python utils (App, logging, config, etc.)"
    project_slug: "nicfit.py"
    py26: "no"
    py27: "no"
    py33: "no"
    py34: "no"
    py35: "yes"
    py36: "yes"
    py37: "yes"
    py_module: "nicfit"
    pypi_repo_name: "nicfit.py"
    pypi_username: "nicfit"
    release_date: "today"
    src_dir: "."
    use_bitbucket: "no"
    use_github: "yes"
    use_make: "yes"
    use_paver: "no"
    use_pypi_deployment_with_travis: "no"
    use_pytest: "yes"
    use_rtd: "no"
    use_travis_ci: "yes"
    version: "0.5.1-beta"
    web: "https://github.com/nicfit/nicfit.py"
    year: "2016-2017"
